Plate_Detection/Plate_Detection/urls.py
from django.contrib import admin

from django.conf.urls import url

from django.conf.urls import include

from plate_app import views



urlpatterns = [
    
    url(r'^$',views.home_page, name ="home_page"),
    url(r'^admin/', admin.site.urls),
    url(r'^algorithm/',include('plate_app.urls')),
    url(r'^login/$' ,views.user_login, name="user_login"),
    url(r'^introduction/' , views.introduction_page , name ="introduction_page"),
    url(r'^logout/$',views.user_logout, name ="logout"),
    url(r'^special/',views.special ,name ="special")
    
]

Plate_Detection/plate_app/urls.py
from django.conf.urls import url
from plate_app import views
from django.conf.urls import include

app_name = 'basic_app'

urlpatterns = [
    url(r'^$',views.algorithm_page , name="algorithm_page"),
    
    url(r'^machine_learing/',views.machine_learing , name ="machine_learing"),
    url(r'^more/' , views.more_page , name ="more"),
    url(r'^register/$' ,views.register,name='register'),
    # url(r'^user_login/$',views.index1,name= "user_login"),
    
]
 

Plate_Detection/plate_app/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.



class UserProfileInfo(models.Model):
    
      
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    #additional
    
    portfolio_site = models.URLField(blank=True)
    
    profile_pic =models.ImageField(upload_to ='profile_pics',blank=True)
    
    def __str__(self):
        return self.user.username

Plate_Detection/plate_app/views.py
from django.shortcuts import render

from django.http import HttpResponse,HttpResponseRedirect

from django.urls import reverse



from django.contrib.auth.decorators import login_required

from django.contrib.auth import authenticate,login,logout

from plate_app.login_form import UserForm,UserProfileInfoForm


# Create your views here.

def home_page(request):
    return render(request, 'basic_html/introduction.html')


def introduction_page(request):
    return render(request,'basic_html/base.html')

def algorithm_page(request):
    return render(request,'basic_html/algorithm.html')


def machine_learing(request):
    return render(request,'basic_html/machine_learing.html')

def more_page(request):
    return render(request,'basic_html/more.html')


def register(request):
    
    registered = False
    
    if request.method == "POST":
        
        user_form = UserForm(data = request.POST)
        
        #profile_form =UserProfileInfoForm(data = request.POST)
        
        if user_form.is_valid(): #and profile_form.is_valid():
            
            user =user_form.save()
            user.set_password(user.password) #convert normal password into hash 
            user.save()
            
            #profile = profile_form.save(commit =False)
            
            profile.user =user
            
            #if 'profile_pic' in request.FILES:
                
                #profile.profile_pic =request.FILES['profile_pic']
                
            #profile.save()
            
            registered =True  
            
        #else:
            
           # print(user_form.errors,profile_form.errors) 
            
    else:
        
        user_form = UserForm()
        #profile_form = UserProfileInfoForm()
    
    return render(request,'basic_html/registration.html',{'user_form':user_form ,'registered':registered}) #'profile_form':profile_form,
        
@login_required              
def special(request):
    return HttpResponse("You are Login")
             
                
@login_required           
def user_logout(request):
    
    logout(request)
    return HttpResponseRedirect(reverse('home_page'))
                  
def index1(request):
    return render(request,'basic_html/login.html')           
            


def user_login(request):
    
    if request.method =='POST':
        
        username = request.POST.get('username')
        
        password = request.POST.get('password')
        
        user=authenticate(username=username,password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home_page'))
                
            else:
                return HttpResponse('ACCOUNT IS NOT ACTIVE')
            
        else:
            print('some one tried to login and fail')
            return HttpResponse("invalid login detail supplied")
        
    else:
        
        return render(request,'basic_html/login.html')
                

Plate_Detection/templates/basic_html/for_intern_template_3.html
<!DOCTYPE html>
<html lang="en">
<title>Plate Detection</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="for_intern_3.scss" rel="stylesheet">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<body>

  <nav class="navbar navbar-fixed-top">
    <div class="container-fluid" style="background-color:#000000e3;">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Home</a>
      </div>
      <ul class="nav navbar-nav">
        <li class=""><a href="#">Introduction</a></li>
        <li><a href="#">Algorithm</a></li>
        <li><a href="#">Machine Learning</a></li>
        <li><a href="#">More</a></li>
      </ul>
      <div class="sign_up_and_search" style="padding-left: 65%;">
        <form class="navbar-form navbar-left" action="/action_page.php">
          <div class="form-group" style="margin-left:px;">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default" style="margin-left:5px">Submit</button>
          <button type="submit" class="btn btn-default" style="margin-left:5px">Login</button>
        </form>
      </div>
    </div>
  </nav>
  <!-- Navbar -->
  <!-- <div class="nav_bar_top"> -->
  <!-- <div class="nav_bar" style="padding:3px; padding-top:30px "> -->
  <!-- <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-red" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a> -->
  <!-- <a href="#" class="w3-bar-item w3-button w3-padding-large w3-white">Home</a> -->
  <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" >Introduction</a> -->
  <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Algorithm</a> -->
  <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Machine Learning</a> -->
  <!-- <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">More</a> -->
  <!-- </div> -->
  <!-- w3-hide-small -->
  <!-- Navbar on small screens -->
  <!-- <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large"> -->
  <!-- <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 1</a> -->
  <!-- <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 2</a> -->
  <!-- <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 3</a> -->
  <!-- <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 4</a> -->
  <!-- </div> -->
  <!-- </div> -->

  <!-- Header -->
  <!-- style="padding:128px 16px " -->

  <header class="w3-container  w3-center" style="padding:300px 16px ; 

    background-size: 100% 100%;
    background-position: center;
    background: linear-gradient(45deg, rgba(30,206,230,0) 0%, rgb(98, 0, 255) 100%);">

    <h1 class="w3-margin w3-jumbo">License Plate Detection</h1>
    <p class="w3-xlarge">Using Convolutional neural network</p>
    <button class="w3-button w3-black w3-padding-large w3-large w3-margin-top">Get Code</button>
  </header>

  <!-- w3-button w3-black w3-padding-large w3-large w3-margin-top -->
  <!-- First Grid -->
  <div class="w3-row-padding w3-padding-64 w3-container">
    <div class="w3-content">
      <div class="w3-twothird">
        <h1 style="padding-bottom: 12%;">INTRODUCTION</h1>
        <p class="text">As India goes through a phase of modernization and infrastructure
          development in the upcoming decade we see significant opportunities
          for the various government entities municipalities and businesses to
          embrace ANPR.Unlike other countries India with its one billion population has a
          unique set of need for ANPR. The main use of ANPR is on highway
          monitoring parking management and neighborhood law enforcement security.
        </p>
        <!-- w3-text-grey -->
        <!-- w3-padding-32 -->
        <p class="text">In India there is one death in every 4 minutes with most of them
          occurring due to over speeding. ANPR is used to monitor the vehicles
          average speed and can identify the vehicle that exceed the speed limit.

        </p>
        <p class="text">
          In this case a fine ticket can be automatically generated by calculating the
          distance between the two cameras. This helps to maintain law and order
          which, in turn, can minimize the number of road casualties. It can support
          a cloud-based system pre-book and pre-pay platform for parking.
        </p>


      </div>

      <!-- <div class="w3-third w3-center">

      <i class="fa fa-anchor w3-padding-64 w3-text-red"></i>
      </div> -->
    </div>
  </div>
  <div class="w3-row-padding  w3-padding-64 w3-container">
    <div class="w3-content">


      <div class="">
        <h1 class="pad_one">OJECTIVE</h1>
        <p class="text">The main objective of this project is to design an efficient automatic
          authorized vehicle identification system using the vehicle number
          plate. The system is implemented on the entrance for security
          control of a highly restricted area like Military Zones, or area around
          top Government offices, e.g., Parliament, Supreme Court etc. </p>
        <p class="text">
          The developed system first detects the vehicle and then captures the
          vehicle image. Vehicle number plate region is extracted using the
          image segmentation in an image. Optical character recognition
          technique is used for the character recognition. This system has been
          implemented in many countries like U.S.A, Europe, Korea, and few
          others. However, for License plate recognition system to work in
          Indian Roads, it should have the capability to identify the License
          plate in dynamic conditions.
        </p>
        <p class="text">
          The proposed system provides a
          foundation for implementing automatic number plate recognition
          system using image processing which can greatly enhance the
          capability of police to detect criminal activities that involves the use
          of motor vehicles. It also reduce the traffic near the toll checkpoints
          areas.
        </p>
      </div>
      <div class="three_major_system_container">
        <p id="three_major_system" class="text">The proposed system has three major stages:</p>
        <ol>
          <li class="text">License Plate Detection using OpenCV</li>
          <li class="text">Character Segmentation</li>
          <li class="text">Character Recognition using Convolutional Neural Network (CNN)</li>
        </ol>
      </div>
      <div class="our_product">
        <p class="text">
          Our Product can be implemented on the entrance for security control
          of a highly restricted area like Military Zones, or area around top
          Government offices, e.g., Parliament, Supreme Court, etc.The main
          objective of our project is to design a low cost and high accuracy
          automatic authorized vehicle identification system using the vehicle
          number plate which can be used in dynamic conditions such as in
          India.The efficiency of most of the plate recognition systems is poor
          particularly for Indian License Plates which are generally highly
          complex in localizing the plate area, segmenting the characters within
          the license plate and the character recognition of segmented
          characters as a valid license plate number (a valid sequence ofASCII characters as plate number to be stored
          in a database for later
          use).
        </p>


      </div>
    </div>
  </div>


  <!-- Second Grid -->
  <div class="w3-row-padding  w3-padding-64 w3-container">
    <div class="w3-content">
      <div class="w3-third w3-center">
        <div class="w3-padding-64 w3-text-red w3-margin-right style">

        </div>
      </div>

      <div class="w3-twothird">
        <h1>License Plate Detection</h1>
        <p class="text">
          We have to resize the captured image in to Required Size and then
          grayscale it resizing help us to avoid any problems with bigger resolution
          images, make sure the number plate still remains in the frame after
          resizing. Gray scaling is common in all image processing steps. This
          speeds up other following process since we no longer have to deal with
          the many color details when processing an image. The image would be
          transformed in two colours black and White. Every image will have useful
          and useless information, in this case for us only the license plate is the
          useful information the rest are pretty much useless for our program. This
          useless information is called noise. Normally using bilateral filter it will
          remove unwanted details from image. The next step is to perform edge
          detection and then start looking for contours on our image. Once the
          counters have been detected we sort them from big to small and consider
          only the first 10 results ignoring the others. In our image the counter could
          be anything that has a closed surface but of all the obtained results the
          license plate number will also be there since it is also a closed surface
        </p>
        <p class="text">
          To filter the license plate image among the obtained results, we will loop
          though all the results and check which has a rectangle shape contour with
          four sides and closed figure. Since a license plate would definitely be a
          rectangle four sided figure
        </p>

      </div>
      <div class="img_of_mode">
        <img src="abc.png" alt="">
      </div>
    </div>
  </div>

  <div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
    <h1 class="w3-margin w3-xlarge">Quote of the day: live life</h1>
  </div>

  <!-- Footer -->
  <footer class="w3-container w3-padding-64 w3-center w3-opacity">
    <div class="w3-xlarge w3-padding-32">
      <i class="fa fa-twitter w3-hover-opacity"></i>
      <i class="fa fa-linkedin w3-hover-opacity"></i>
    </div>
  </footer>

  <script>
    // Used to toggle the menu on small screens when clicking on the menu button
    function myFunction() {
      var x = document.getElementById("navDemo");
      if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
      } else {
        x.className = x.className.replace(" w3-show", "");
      }
    }
  </script>

</body>

</html>

Plate_Detection/templates/basic_html/index.html
<!DOCTYPE html>

{% extends "basic_html/base.html" %}

    {% block body_block %}
        <h1>welcome to index</h1>
        <h2>this is example of inheritance</h2>
    
    
    {% endblock %}

Plate_Detection/templates/basic_html/introduction.html
<!DOCTYPE html>
<html>

<head>
    <title>Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        body {
            position: relative;
        }


        #section1 {
            padding-bottom: 20%;
            padding-top: 10%;
            height: 500px;
            color: #fff;
            background-color: #1E88E5;
            word-spacing: 10px;
        }

        #section2 {
            padding-bottom: 20%;
            padding-top: 10%;
            color: #fff;
            background-color: #673ab7;
            word-spacing: 10px;
        }

        #section3 {
            padding-bottom: 20%;
            padding-top: 10%;
            color: #fff;
            background-color: #009688;
            word-spacing: 10px;
            ;
        }

        #section4 {
            padding-bottom: 20%;
            padding-top: 10%;
            color: #fff;
            background-color: #006b96;
            word-spacing: 10px;
        }
    </style>
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="50">

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li><a href="#section1">Introduction</a></li>
                        <li><a href="#section2">Project Abstract</a></li>
                        <li><a href="#section3">Technical Details</a></li>
                        <li><a href="#section4">More</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <div id="section1" class="container-fluid" style="padding-bottom: 40%;">
        <h1 style="margin-left:35%; margin-right:35%; padding-bottom:5%; padding-top:8%">INTRODUCTION</h1>
        <div class="well well-sm" style="margin-left: 25%; margin-right:30%; padding-left:3%; padding-right:2%"><a
                href="{% url 'introduction_page' %}" style=" text-decoration: none;">
                <h3>License Plate Detection & Recognition</h3>
            </a></div>


    </div>
    <div id="section2" class="container-fluid" style="padding-bottom: 20%;">
        <h1 style="padding-left:35%; padding-right:35%; padding-bottom:5%">Project Abstract</h1>
        <p style="font-size:large; padding-left:5%; padding-right:5%">The main objective of this project is to design an
            efficient automatic
            authorized vehicle identification system using the vehicle number
            plate. The system is implemented on the entrance for security
            control of a highly restricted area like Military Zones or area around
            top Government offices e.g Parliament, Supreme Court </p>
        <p style="font-size:large; padding-left:5%; padding-right:5%">The
            developed system first detects the vehicle and then captures the
            vehicle image. Vehicle number plate region is extracted using the
            image segmentation in an image. Optical character recognition
            technique is used for the character recognition. This system has been
            implemented in many countries like U.S.A, Europe, Korea, and few
            others. However, for License plate recognition system to work in
            Indian Roads, it should have the capability to identify the License
            plate in dynamic conditions </p>
        <p style="font-size:large; padding-left:5%; padding-right:5%"> The proposed system provides a
            foundation for implementing automatic number plate recognition
            system using image processing which can greatly enhance the
            capability of police to detect criminal activities that involves the use
            of motor vehicles. It also reduce the traffic near the toll checkpoints
            areas</p>
        <p style="font-size:x-large; padding-left:5%; padding-right:5%">The proposed system has three major stages :</p>
        <ul style="font-size:large; padding-left:7%; padding-right:5%">
            <li>License Plate Detection using OpenCV</li>
            <li>Character Segmentation</li>
            <li>Character Recognition using Convolutional Neural Network
                (CNN)</li>
        </ul>


    </div>
    <div id="section3" class="container-fluid" style="padding-bottom: 20%;">
        <h1 style="padding-left:35%; padding-right:35%; padding-bottom:5%">Technical Details</h1>
        <h2 style="padding-left: 5%; padding-bottom:2%; padding-top:3%">License Plate Detection :</h2>
        <p style="font-size:large; padding-left:5%; padding-right:5%">We have to resize the captured image in to
            Required Size and then
            grayscale it resizing help us to avoid any problems with bigger resolution
            images, make sure the number plate still remains in the frame after
            resizing. Gray scaling is common in all image processing steps. This
            speeds up other following process since we no longer have to deal with
            the many color details when processing an image. The image would be
            transformed in two colours black and White. Every image will have useful
            and useless information, in this case for us only the license plate is the
            useful information the rest are pretty much useless for our program. This
            useless information is called noise. Normally using bilateral filter it will
            remove unwanted details from image. The next step is to perform edge
            detection and then start looking for contours on our image. Once the
            counters have been detected we sort them from big to small and consider
            only the first 10 results ignoring the others. In our image the counter could
            be anything that has a closed surface but of all the obtained results the
            license plate number will also be there since it is also a closed surface.</p>
        <p style="font-size:large; padding-left:5%; padding-right:5%">To filter the license plate image among the
            obtained results, we will loop
            though all the results and check which has a rectangle shape contour with
            four sides and closed figure. Since a license plate would definitely be a
            rectangle four sided figure.
        </p>
        <h2 style="padding-left: 5%; padding-bottom:2%; padding-top:3%">Character Segmentation & Feature Extraction :
        </h2>
        <p style="font-size:large; padding-left:5%; padding-right:5%"> Character segmentation is an operation that seeks
            to decompose an image
            of a sequence of charac- ters into subimages of individual symbols. It is
            one of the decision processes in a system for optical character recognition
            (OCR)</p>
        <p style="font-size:large; padding-left:5%; padding-right:5%">In feature extraction stage each character is
            represented as a feature
            vector which becomes its identity. The major goal of feature extraction is to extract a set of features,
            which maximizes the recognition rate with the
            least amount of elements.</p>
        <h2 style="padding-left: 5%; padding-bottom:2%; padding-top:3%">Character Recognition Using CNN :</h2>
        <p style="font-size:large; padding-left:5%; padding-right:5%">In order to predict the character present in
            Number plate we use Machine
            learning Technique called CNN (Convolutional Neural Network). In deep
            learning, a convolutional neural network is a class of deep neural
            networks, most commonly applied to analyzing image.</p>

    </div>
    <div id="section4" class="container-fluid" style="padding-bottom: 30%;">
        <h1 style="padding-left:35%; padding-right:35%; padding-bottom:5%; margin-left:8%; margin-right:8%;">MORE</h1>

        <div class="well well-sm" style="margin-left: 27%; margin-right:35%; padding-left:10%; padding-right:10%"><a
                href="{% url 'basic_app:machine_learing' %}" style=" text-decoration: none;">
                <h3>Machine Learning</h3>
            </a></div>
        <div class="well well-sm" style="margin-left: 27%; margin-right:35%; padding-left:10%; padding-right:10%"><a
                href="{% url 'basic_app:machine_learing' %}" style=" text-decoration: none;">
                <h3>C++ Tutorial</h3>
            </a></div>

        <div class="well well-sm" style="margin-left: 27%; margin-right:35%; padding-left:10%; padding-right:10%"><a
                href="{% url 'basic_app:machine_learing' %}" style=" text-decoration: none;">
                <h3>Python Tutorial</h3>
            </a></div>
        <div class="well well-sm" style="margin-left: 27%; margin-right:35%; padding-left:10%; padding-right:5%"><a
                href="{% url 'introduction_page' %}" style=" text-decoration: none;">
                <h3>Go To Main Project</h3>
            </a></div>

    </div>


</body>

</html>

Plate_Detection/templates/basic_html/login.html
<!DOCTYPE html>
{% extends 'basic_html/base.html' %}

{% block body_block %}

<div class="jumbotron">

    <!-- <form action="{% url 'user_login' %}" method="post">

        {% csrf_token %}

        <label for="username">UserName</label>
        <input type="text" name="username" placeholder="Enter UserName">

        <label for="password">Password</label>
        <input type="text" name="password">
        <input type="Submit" class="btn btn-primary" value="login">


    </form>  -->
    <div class="container" style="padding-top:12%; padding-bottom:10%">
        <h2>LOGIN PAGE</h2>
        <h3></h3>
        <form action="{% url 'user_login' %}" method="post" >
            {% csrf_token %}
            <div class="form-group">
                <label for="username">UserName</label>
                <input type="text" placeholder="UserName" name="username">
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" placeholder="Enter password" name="password">
            </div>
            <div class="checkbox">
                <label><input type="checkbox" name="remember"> Remember me</label>
            </div>

            <input type="Submit" class="btn btn-primary" value="login">
            <!-- <input type="submit" name="" value="Login"> -->
        </form>
    </div> 

</div>

{% endblock %}

Plate_Detection/templates/basic_html/machine_learing.html
<!DOCTYPE html>

{% extends "basic_html/base.html" %}

{% block body_block %}
<div class="container-fluid text-center">
    
    <div class="row content" style="padding-top: 10%; padding-bottom:10%;">
        <div class="container_for_side" >

        </div>
        <div class="" style="font-family:'Roboto',sans-serif; font-size:16px;
        text-align: left; color: rgba(0,0,0,.84); padding-left:5%; padding-right:5%">
            <h1 style="font:35px solid black">Machine learning</h1>
            <p style="padding-top:3%;">Machine Learning is the field of study that gives computers the capability to learn without being explicitly programmed.
                ML is one of the most exciting technologies that one would have ever come across. 
                As it is evident from the name, it gives the computer that makes it more similar to humans: The ability to learn.
            </p>
            <label for="">for more</label>
            <a href="https://en.wikipedia.org/wiki/ML">click here</a>
            <!-- <img src="abc.jpg" alt="Don't show"> -->
            <h3 style="padding-top:5%; padding-bottom:5%; font:26px solid black">Introduction To Machine Learning</h3>
            <div class="well well-sm"> 1 <a href="">Data Preprocessing</a></div>
            <div class="well well-sm"> 2 <a href="">Simple Linear Regression</a></div>
            <div class="well well-sm"> 3 <a href="">Multiple Linear Regression</a></div>
            <div class="well well-sm"> 4 <a href="">Polynomial Regression</a></div>
            <div class="well well-sm"> 5 <a href="">Support Vector Regression (SVR)</a></div>
            <div class="well well-sm"> 6 <a href="">Decision Tree Regression</a></div>
            <div class="well well-sm"> 7 <a href="">Random Forest Regression</a></div>
            <div class="well well-sm"> 8 <a href="">Evaluating Regression Models Performance</a></div>
            <div class="well well-sm"> 9 <a href="">Logistic Regression</a></div>
            <div class="well well-sm"> 10 <a href="">K-Nearest Neighbors (K-NN)</a></div>
            <div class="well well-sm"> 11 <a href="">Support Vector Machine (SVM)</a></div>
            <div class="well well-sm"> 12 <a href="">Kernel SVM</a></div>
            <div class="well well-sm"> 13 <a href="">Naive Bayes</a></div>
            <div class="well well-sm"> 14 <a href="">Decision Tree Classification</a></div>
            <div class="well well-sm"> 15 <a href="">Random Forest Classification</a></div>
            <div class="well well-sm"> 16 <a href="">Evaluating Classification Models Performance</a></div>
            <div class="well well-sm"> 17 <a href="">K-Means Clustering</a></div>
            <div class="well well-sm"> 18 <a href="">Hierarchical Clustering</a></div>
            <div class="well well-sm"> 19 <a href="">Association Rule Learning Apriori</a></div>
            <div class="well well-sm"> 20 <a href="">Reinforcement Learning Upper Confidence Bound (UCB)</a></div>
            <div class="well well-sm"> 21 <a href="">Reinforcement Learning Thompson Sampling</a></div>
            <div class="well well-sm"> 22 <a href="">Artificial Neural Networks</a></div>
            <div class="well well-sm"> 23 <a href="">Convolutional Neural Networks</a></div>
            <div class="well well-sm"> 24 <a href="">Dimensionality Reduction Principal Component Analysis (PCA)</a></div>
            <div class="well well-sm"> 25 <a href="">Dimensionality Reduction Linear Discriminant Analysis (LDA)</a></div>
            <div class="well well-sm"> 26 <a href="">Model Selection & Boosting </a></div>
            <div class="well well-sm"> 27 <a href="">XGBoost</a></div>
        </div>
        
    </div>
</div>


{% endblock %}

Plate_Detection/templates/basic_html/registration.html
<!DOCTYPE html>

{% extends 'basic_html/base.html' %}

{% load static %}

{% block body_block %}

<div class="jumbotron">

    {% if registered %}

        <h1>thank you for registering</h1>
    {% else %}

        <h1>register here!</h1>
        <h3>Fill out the form</h3>

        <form method="post" enctype="multipart/form-data">
        
            {% csrf_token %}
            {{user_form.as_p}}
            <!-- {{profile_form.as_p}} -->

            <input type="submit" name="" value="Register">



        
        </form>
    {% endif %}

</div> 

{% endblock %}